# Generated by Django 5.2.7 on 2025-12-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_voter_user_voter_has_voted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
